### ISSUE TITLE
TODO - Hardware

### ISSUE THREAD

**Issue by Jonny999999** [Jonny999999/waterpump#1]
- CAD
  - [x] design distribution box  pump
  - [x] design servo - valve mount
  - [x] design user interface panel insert
  - [x] design housing / mount for pcb inside cabinet
  - [ ] design caps for  closing holes cabinet

- ELECTRICAL
  - [x] re-wire vfd
  - [x] wire pump components to distribution box
    - [x] pressure sensor
    - [x] flow sensor
    - [x] servo
  - [x] pin assignment parallel port cable
  - [x] pin assignment cable vfd control

- MECHANICAL
  - [x] replace broken valves
  - [x] clean cabinet
  - [x] lid for cabinet floor
  - [x] pipe assembly top
  - [x] pipe assembly bottom
  - [x] pipe assembly reservoir
  - [x] attach hoses
